### PR TITLE
udev: fidodev: Add Ledger NanoS+ and Stax

### PR DESCRIPTION
**Pull request by xchapron-ledger**

### CODE REVIEW

**Review by sportron-ledger — COMMENTED** [review]
LGTM

**Comment by xchapron-ledger** [comment]
@LDVG Hello, I'm not sure who to ping on this? Can you have a look?
Thanks!

**Comment by xchapron-ledger** [comment]
> Thanks for the PR!

@kongeo  Thanks! Do you know when a new released is expected?

**Comment by kongeo** [comment]
That I do not know yet, we will discuss internally and come back to it towards the end of the month.

**Pull request merged**
