### PR TITLE
Add support for Windows shared lib

### LINKED ISSUE #21: No Shared Library Available for Windows
I noticed that support for Windows shared library is explicitly disabled in the CMake project.  I made some trivial changes locally and using this library as a shared library on Windows doesn't seem to cause any issues so why is it disabled?  If it is because of lack of familiarity with Windows builds then I would be happy to submit a PR for review.

The reason I want it as a shared library is because I wrote a set of .NET bindings to allow use of the library from .NET languages but the ability to link statically is not available to .NET projects.

### PR DESCRIPTION
**Pull request by borrrden**
Closes #21 

Also adds a proper build script for Windows

### CODE REVIEW

**Comment by martelletto** [comment]
Thank you for the PR! One thing I noticed is that the statically linked examples, which used to work when linked against the debug runtime and to behave inconsistently when built with --config Release (issue #20), no longer work. When I try to execute them, I am presented with a dialog reading "The application was unable to start correctly (0xc000007b)", regardless of the runtime they are linked against. I plan to look further into this (and the PR as a whole) tomorrow. Perhaps you know why that's happening?

**Comment by borrrden** [comment]
I am able to build and run (at least) manifest.exe fine using my script that I submitted.  I tweaked it a bit when it failed to behave properly on another machine and I realized that since you are already using export lists for other platforms I should simply be using them for MSVC as well.  That will be *a lot* cleaner.  I will update the PR but as for the other issue, it's more to do with the way the build is set up.  It would be better to have these two deps as CMake subdirectories so that they always get built with the correct configuration (more detailed comment on the issue itself)

**Comment by borrrden** [comment]
P.S. I believe the particular problem you face could possibly be missing crypto-44.dll.  Windows is annoying about its search paths so even if it was found at link time it might not be found at runtime.  For cred.exe, in particular, the file needs to be adjacent to cred.exe

**Comment by martelletto** [comment]
You are absolutely right; that was indeed the problem. Thank you!

**Pull request merged**
