### PR TITLE
Add compile and link options

### PR DESCRIPTION
**Pull request by silkeh**
Add CMake options to disable:

- The building of static and/or dynamic libraries.
- The building of the tools.
- The building of the examples.
- The building of the man pages.

This allows for situations where the building of the examples, tools or dynamic/static libraries is not wanted.

### CODE REVIEW

**Comment by silkeh** [comment]
An important note: the `cred` example only builds against the static library.
This might be caused by my particular build environment, and fixing this is probably out of scope for this PR (unless trivial).

The following error is thrown when built against the shared or system library:

```
[72/84] Linking C executable examples/cred
FAILED: examples/cred 
: && /usr/bin/cc -Wall -Wextra -Werror -Wshadow -Wwrite-strings -Wmissing-prototypes -Wbad-function-cast -pedantic -pedantic-errors -fstack-protector-all -std=c99 -Wno-unused-result -Wcast-qual -Wl,-z,noexecstack -Wl,-z,relro,-z,now   -rdynamic examples/CMakeFiles/cred.dir/cred.c.o examples/CMakeFiles/cred.dir/util.c.o examples/CMakeFiles/cred.dir/__/openbsd-compat/clock_gettime.c.o examples/CMakeFiles/cred.dir/__/openbsd-compat/getopt_long.c.o examples/CMakeFiles/cred.dir/__/openbsd-compat/strlcat.c.o examples/CMakeFiles/cred.dir/__/openbsd-compat/strlcpy.c.o -o examples/cred  -Wl,-rpath,/home/silex/Development/misc/libfido2/build/src  src/libfido2.so.1.5.0  -lcbor  -lcrypto  -ludev  -lrt && :
/usr/bin/ld: examples/CMakeFiles/cred.dir/cred.c.o: in function `main':
cred.c:(.text+0x35b): undefined reference to `fido_dev_new_with_info'
/usr/bin/ld: cred.c:(.text+0x368): undefined reference to `fido_dev_open_with_info'
collect2: error: ld returned 1 exit status
```

Result table (without `MANPAGES`) for convenience:


| Result | `STATIC` | `SHARED` | `EXAMPLES` | `TOOLS` |
|--------|----------|----------|------------|---------|
| -      | off      | off      | off        | off     |
| Ok     | on       | off      | off        | off     |
| Ok     | off      | on       | off        | off     |
| Ok     | on       | on       | off        | off     |
| Fail   | off      | off      | on         | off     |
| Ok     | on       | off      | on         | off     |
| Fail   | off      | on       | on         | off     |
| Ok     | on       | on       | on         | off     |
| Ok     | off      | off      | off        | on      |
| Ok     | on       | off      | off        | on      |
| Ok     | off      | on       | off        | on      |
| Ok     | on       | on       | off        | on      |
| Fail   | off      | off      | on         | on      |
| Ok     | on       | off      | on         | on      |
| Fail   | off      | on       | on         | on      |
| Ok     | on       | on       | on         | on      |

**Comment by martelletto** [comment]
For my own education:

- Is there a specific reason you prefixed `_FIDO2_LIBRARY` with `_`? Is this a CMake convention I am not aware of?
- Are descriptions passed to `option()` made available somewhere by cmake(1)?

Thank you!

-p.

**Comment by silkeh** [comment]
> * Is there a specific reason you prefixed `_FIDO2_LIBRARY` with `_`? Is this a CMake convention I am not aware of?

The reason is to mark that it is a temporary internal variable. From [the docs](https://cmake.org/cmake/help/v3.0/manual/cmake-developer.7.html): "For internal implementation, it’s a generally accepted convention that variables starting with underscore are for temporary use only."
 
>  * Are descriptions passed to `option()` made available somewhere by cmake(1)?

Yes: `cmake -LH`

```
// Build example programs
BUILD_EXAMPLES:BOOL=ON

// Build man pages
BUILD_MANPAGES:BOOL=ON

// Build the shared library
BUILD_SHARED_LIBS:BOOL=ON

// Build the static library
BUILD_STATIC_LIBS:BOOL=ON

// Build tool programs
BUILD_TOOLS:BOOL=ON

// Choose the type of build, options are: None Debug Release RelWithDebInfo MinSizeRel ...
CMAKE_BUILD_TYPE:STRING=

// Install path prefix, prepended onto install directories.
CMAKE_INSTALL_PREFIX:PATH=/usr/local

// Path to a program.
GZIP_PATH:FILEPATH=/usr/bin/gzip

// Path to a program.
MANDOC_PATH:FILEPATH=MANDOC_PATH-NOTFOUND
```

**Comment by martelletto** [comment]
Thank you!

**Pull request merged**
