### PR TITLE
get libfido2 w/ WebAuthn support running on Cygwin/MSYS again

### PR DESCRIPTION
**Pull request by github-cygwin**
So far the Cygwin distro has been packaging libfido2 version 1.5.0.
A lot has happened in the meantime, the most important step for us
the support for WebAuthn.

Unfortunately, Cygwin (and it's fork MSYS) haven't been taken into
account while creating WebAuthn support.  This patch series is
supposed to fix this.  It contains 9 patches, some of them just to
support GCC (especially with -Werror -Wextra), some of them to
support Cygwin/MSYS.

I hope the patchset is ok for you.

Thanks,
Corinna

### CODE REVIEW

**Comment by github-cygwin** [comment]
So the builds fail on native Windows, but the error output is missing details.  I only see "Error:", nothing else.  Does somebody have more access to the actual error output?

**Comment by martelletto** [comment]
I am AFK at the moment, but at a glance:

```
D:\a\libfido2\libfido2\src\winhello.c(84,36): error C2220: the following warning is treated as an error [D:\a\libfido2\libfido2\build\x64\dynamic\src\fido2_shared.vcxproj]
D:\a\libfido2\libfido2\src\winhello.c(84,36): warning C4113: 'DWORD (__cdecl *)()' differs in parameter lists from 'DWORD (__cdecl *)(void)' 
```

I am attaching the full logs. Thank you for your work and apologies for the breakage.

[logs_11943.zip](https://github.com/Yubico/libfido2/files/7540243/logs_11943.zip)

**Comment by github-cygwin** [comment]
> I am AFK at the moment, but at a glance:
> 
> ```
> D:\a\libfido2\libfido2\src\winhello.c(84,36): error C2220: the following warning is treated as an error [D:\a\libfido2\libfido2\build\x64\dynamic\src\fido2_shared.vcxproj]
> D:\a\libfido2\libfido2\src\winhello.c(84,36): warning C4113: 'DWORD (__cdecl *)()' differs in parameter lists from 'DWORD (__cdecl *)(void)' 
> ```

Oh, darn, there's a "void" missing, apparently.  I'll fix that and force push the patch, and then let's see what happens...

> I am attaching the full logs. Thank you for your work and apologies for the breakage.

No worries, and thanks!

Corinna

**Comment by github-cygwin** [comment]
"All checks have passed"

Yay!

**Comment by martelletto** [comment]
Thank you for the PR. I have cherry-picked commits 887c8b5, bdb005c, 7d0a0f4, 93eb981, and 9272372, with only minor modifications (whitespace, `unsigned long` -> `u_long`). While I agree they serve no practical purpose, I believe the checks removed in fca5e36 are important and would prefer to keep them if possible. Regarding 2d7ad94 and 01108e7, I have pushed a branch with suggestions: https://github.com/Yubico/libfido2/compare/cygwin-suggestions. If there are no objections, I would like to squash the suggestions with the original commits and merge the results.

**Comment by github-cygwin** [comment]
> While I agree they serve no practical purpose, I believe the checks removed in [fca5e36](https://github.com/Yubico/libfido2/commit/fca5e368ca9b3947938361755ab0d19da6cae6a9) are important and would prefer to keep them if possible.

The problem is this: They don't only serve any purpose, they also break the build, because GCC complains about
the range.  Range-checking against values which are outside the range of the incoming data type are just errors
with -Werror.

**Comment by martelletto** [comment]
IIRC, the warnings are caused by `-Wtype-limits` (gcc) and `-Wtautological-constant-out-of-range-compare` (clang). Does 46ee2c73 look any better?

**Comment by github-cygwin** [comment]
> IIRC, the warnings are caused by `-Wtype-limits` (gcc) and `-Wtautological-constant-out-of-range-compare` (clang). Does [46ee2c7](https://github.com/Yubico/libfido2/commit/46ee2c732b9d12abe3c3cd4992c0451c07fd41c4) look any better?

Let me check by performing a full distro build of the package...

**Comment by github-cygwin** [comment]
Build still fails with

```
winhello.c:83:41: error: ISO C forbids conversion of function pointer to object pointer type [-Wpedantic]
   83 |         if ((webauthn_get_api_version = (void *)GetProcAddress(webauthn_handle,
[...]              
```

These casts to void * are really wrong.  The function pointer is cast two times instead of
only once, because the result is again a function pointer.  Just dropping -pedantic is not the way
to go, IMHO.  Casting correctly is much better.

Please consider commit db5c2d6051af from the original patchset, maybe just with slightly
different formatting?

Thanks,
Corinna

**Comment by github-cygwin** [comment]
Oh, btw., that's the only problem left!

Thanks,
Corinna

**Comment by martelletto** [comment]
Thanks for testing. I installed Cygwin in the meantime and ran into the same error. IMHO, the casts are fine and the warning is wrong :) (FWIW, the person responsible for the introduction of the warning in gcc agrees with me: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=11234#c10), but let's not get stuck on that. I will reformat db5c2d6 to try to make the casts a bit easier on the eyes.

**Comment by martelletto** [comment]
I have uploaded the resulting branch (squashed and ready to go) to https://github.com/Yubico/libfido2/compare/test-ci. If there are no objections, I would like to push it to your repository's master branch, so that the commits are associated with this PR and our discussion around it. Thanks for the quick feedback and insight.

**Comment by github-cygwin** [comment]
The test-ci branch builds fine on 64 and 32 bit Cygwin.  I like the function pointer typedefs :+1: 

I pushed the changes to my master branch.

Thanks for pulling this through,
Corinna

**Review by LDVG — APPROVED** [review]

**Review by kongeo — APPROVED** [review]

**Pull request merged**
