### PR TITLE
Install pkgconfig files also on msvc

### PR DESCRIPTION
**Pull request by nacho**

### CODE REVIEW

**Comment by nacho** [comment]
These days it is perfectly normal that you might want to build with msvc using meson on windows. By installing the pc file also on windows makes it a lot simpler to build against fido2.

**Comment by nacho** [comment]
That is correct, meson does the translation without any issues.

**Comment by martelletto** [comment]
LGTM

**Review by LDVG — APPROVED** [review]
Thanks for the clarification!

**Pull request merged**
